services:
  client:
    environment:
      - HOST_JWT_SECRET=${HOST_JWT_SECRET}
      - HOST_DB_CONNECT=${HOST_DB_CONNECT}
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - path: .
          target: /app
          action: sync
          ignore:
            - node_modules/
        - path: ./package.json
          action: rebuild

    container_name: pet-server
    ports:
      - '4000:4000'
    volumes:
      - server_uploaded:/app/uploaded

  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  server_uploaded:
